
INFO:root:Epoch 1
/home/brett/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
INFO:root:Epoch [1/50], Step [1/1562], Loss: 0.4901, Time: 1015.36s
INFO:root:Epoch [1/50], Step [2/1562], Loss: 0.4058, Time: 766.44s
INFO:root:Epoch [1/50], Step [3/1562], Loss: 0.3620, Time: 653.07s
INFO:root:Epoch [1/50], Step [4/1562], Loss: 0.3364, Time: 590.92s
INFO:root:Epoch [1/50], Step [5/1562], Loss: 0.3200, Time: 570.94s
INFO:root:Epoch [1/50], Step [6/1562], Loss: 0.3068, Time: 553.82s
INFO:root:Epoch [1/50], Step [7/1562], Loss: 0.2978, Time: 542.24s
INFO:root:Epoch [1/50], Step [8/1562], Loss: 0.2918, Time: 532.95s
INFO:root:Epoch [1/50], Step [9/1562], Loss: 0.2848, Time: 521.44s
INFO:root:Epoch [1/50], Step [10/1562], Loss: 0.2790, Time: 513.03s
INFO:root:Epoch [1/50], Step [11/1562], Loss: 0.2736, Time: 505.00s
INFO:root:Epoch [1/50], Step [12/1562], Loss: 0.2698, Time: 502.34s
INFO:root:Epoch [1/50], Step [13/1562], Loss: 0.2665, Time: 495.21s
INFO:root:Epoch [1/50], Step [14/1562], Loss: 0.2633, Time: 494.39s
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f108d8f7790>
Traceback (most recent call last):
  File "/home/brett/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1479, in __del__
    self._shutdown_workers()
  File "/home/brett/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1443, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/brett/anaconda3/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/brett/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait
    if not wait([self.sentinel], timeout):
  File "/home/brett/anaconda3/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/brett/anaconda3/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/brett/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 44027) is killed by signal: Interrupt.
Process Process-1:
Traceback (most recent call last):
  File "/home/brett/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/brett/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/brett/Desktop/tutorials/ijepa/ijepa/main_ijepa.py", line 54, in process_main
    app_main(args=params)
  File "/home/brett/Desktop/tutorials/ijepa/ijepa/src/train.py", line 452, in main
    (loss, _new_lr, _new_wd, grad_stats), etime = gpu_timer(train_step)
  File "/home/brett/Desktop/tutorials/ijepa/ijepa/src/utils/logging.py", line 21, in gpu_timer
    result = closure()
  File "/home/brett/Desktop/tutorials/ijepa/ijepa/src/train.py", line 440, in train_step
    loss.backward()
  File "/home/brett/anaconda3/lib/python3.8/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/home/brett/anaconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt
INFO:root:Epoch [1/50], Step [15/1562], Loss: 0.2598, Time: 489.83s
INFO:root:Epoch [1/50], Step [16/1562], Loss: 0.2566, Time: 485.71s
INFO:root:Epoch [1/50], Step [17/1562], Loss: 0.2539, Time: 482.36s
INFO:root:Epoch [1/50], Step [18/1562], Loss: 0.2511, Time: 480.57s