2024-06-28 13:44:24,445 INFO    MainThread:9878 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2024-06-28 13:44:24,446 INFO    MainThread:9878 [wandb_setup.py:_flush():76] Configure stats pid to 9878
2024-06-28 13:44:24,446 INFO    MainThread:9878 [wandb_setup.py:_flush():76] Loading settings from /home/brett/.config/wandb/settings
2024-06-28 13:44:24,446 INFO    MainThread:9878 [wandb_setup.py:_flush():76] Loading settings from /home/brett/Desktop/tutorials/ijepa/ijepa/wandb/settings
2024-06-28 13:44:24,446 INFO    MainThread:9878 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2024-06-28 13:44:24,446 INFO    MainThread:9878 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-28 13:44:24,446 INFO    MainThread:9878 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main_ijepa.py', 'program_abspath': '/home/brett/Desktop/tutorials/ijepa/ijepa/main_ijepa.py', 'program': 'main_ijepa.py'}
2024-06-28 13:44:24,446 INFO    MainThread:9878 [wandb_init.py:_log_setup():528] Logging user logs to /home/brett/Desktop/tutorials/ijepa/ijepa/wandb/run-20240628_134424-m0d8tm4v/logs/debug.log
2024-06-28 13:44:24,446 INFO    MainThread:9878 [wandb_init.py:_log_setup():529] Logging internal logs to /home/brett/Desktop/tutorials/ijepa/ijepa/wandb/run-20240628_134424-m0d8tm4v/logs/debug-internal.log
2024-06-28 13:44:24,446 INFO    MainThread:9878 [wandb_init.py:init():568] calling init triggers
2024-06-28 13:44:24,446 INFO    MainThread:9878 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {}
2024-06-28 13:44:24,446 INFO    MainThread:9878 [wandb_init.py:init():618] starting backend
2024-06-28 13:44:24,446 INFO    MainThread:9878 [wandb_init.py:init():622] setting up manager
2024-06-28 13:44:24,451 INFO    MainThread:9878 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-28 13:44:24,452 INFO    MainThread:9878 [wandb_init.py:init():628] backend started and connected
2024-06-28 13:44:24,461 INFO    MainThread:9878 [wandb_init.py:init():720] updated telemetry
2024-06-28 13:44:24,474 INFO    MainThread:9878 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-06-28 13:44:24,672 ERROR   MainThread:9878 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-06-28 13:44:24,805 ERROR   MainThread:9878 [wandb_init.py:init():1188] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/home/brett/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/brett/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-06-28 13:44:25,810 WARNING MsgRouterThr:9878 [router.py:message_loop():77] message_loop has been closed
